server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - 'service-config/*service'
          uri: "https://github.com/madhushika-madhubhani/spring-cloud-config-store"

